version: '3.1'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
