version: '3.1'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env

  api:
    image: asstra/api:latest
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
