apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ara-back
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
      - name: api
        image: asstra/api:latest
        ports:
          - name: tcp
            containerPort: 8080
            protocol: TCP
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: api
                key: database
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: api
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api
                key: password
          - name: POSTGRES_HOST
            value: "db.ara-db"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5