apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: ara-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
        - name: db
          livenessProbe:
            tcpSocket:
              port: tcp
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: password
          image: postgres:15
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: tcp
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: "/data"
              name: db-pv
      volumes:
      - name: db-pv
        persistentVolumeClaim:
          claimName: db-pv-newclaim