kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
