kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pv-newclaim
  labels:
    app: db
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi