name: Build and Push

on:
  push:
    tags:
      - 'apiv*.*'      # Triggers for API versions like apiv1.0, apiv2.1, etc.

jobs:
  build-and-push-api:
    if: startsWith(github.ref, 'refs/tags/apiv')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCRIO_TOKEN }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-api:${{ github.ref_name }}

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io